# LAGOS RICE PRICES

**1. IMPORTING THE REQUIRED LIBRARIES**

In [1]:
import pandas as pd

**2. IMPORTING THE DATASET :** I used the pd.read_csv() function because I am importing a .csv file

In [2]:
filename = "C:/Users/HP/Desktop/DATA SET/lagos_food_prices.csv"

lagos_rice_prices = pd.read_csv(filename)

lagos_rice_prices

,id,ItemLabels,17-Jan,17-Feb,17-Mar,17-Apr,17-May,17-Jun,17-Jul,17-Aug,...,21-Mar,21-Apr,21-May,21-Jun,21-Jul,21-Aug,21-Sep,21-Oct,21-Nov,21-Dec
0,1,Agric eggs medium size,597.00,591.82,586.32,526.32,528.42,526.50,468.24,492.63,...,553.18,568.10,580.00,611.50,676.50,692.50,700.00,735.00,740.06,763.33
1,2,Agric eggs(medium size price of one),50.74,54.14,51.05,49.41,49.28,45.43,40.88,41.18,...,50.38,50.57,51.67,51.58,62.00,58.13,66.47,68.00,70.00,73.18
2,3,"Beans brown,sold loose",416.70,418.10,395.17,358.96,388.76,412.53,424.56,488.13,...,347.67,346.16,358.88,342.38,388.29,484.88,481.76,438.56,440.54,449.63
3,4,Beans:white black eye. sold loose,364.85,354.73,356.56,348.42,386.97,411.22,409.92,402.11,...,343.28,356.32,396.32,386.90,372.81,471.73,497.47,499.63,500.86,511.18
4,5,Beef Bone in,1008.16,1025.56,1124.77,1055.56,1132.64,1169.07,1111.11,1122.83,...,1302.38,1325.44,1343.39,1349.57,1367.76,1393.33,1430.91,1500.27,1500.72,1520.81
5,6,"Beef,boneless",1363.31,1378.88,1320.91,1264.91,1404.39,1472.63,1451.51,1673.78,...,1358.04,1376.79,1327.78,1398.74,1466.91,1569.44,1625.20,1664.26,1678.65,1700.00
6,7,Bread sliced 500g,308.05,304.00,299.52,289.47,294.21,307.62,291.18,272.22,...,360.00,376.32,397.06,365.79,397.37,425.00,402.94,434.21,412.50,428.50
7,8,Bread unsliced 500g,265.81,256.39,259.00,253.89,260.00,250.00,238.00,267.50,...,322.73,315.00,322.22,344.76,352.63,363.33,398.75,395.00,408.33,379.55
8,9,Broken Rice (Ofada),720.61,712.30,709.26,705.56,699.40,698.09,689.31,566.34,...,827.45,898.61,938.61,825.52,844.13,844.36,849.66,869.28,842.50,850.25
9,10,Chicken Feet,998.83,970.00,950.00,916.67,1025.00,1100.00,1140.00,1066.67,...,926.36,966.67,943.75,955.00,980.00,987.50,997.43,1055.56,1060.33,1060.33
10,11,Chicken Wings,1079.07,1098.21,1028.57,1062.13,1065.63,1117.65,1190.00,1200.00,...,1190.48,1168.42,1164.71,1170.00,1200.00,1237.50,1378.57,1421.05,1526.11,1604.76
11,12,Evaporated tinned milk carnation 170g,140.02,126.67,140.00,150.00,152.86,156.67,178.75,156.00,...,185.71,231.25,192.00,194.29,205.71,219.67,220.00,227.50,216.67,240.00
12,13,"Evaporated tinned milk(peak), 170g",145.00,173.36,192.00,196.11,195.71,197.14,195.29,210.00,...,216.36,234.21,220.00,238.57,241.00,248.67,250.59,248.95,268.89,279.39
13,14,Frozen chicken,1172.56,1290.97,1244.44,1378.95,1357.89,1438.10,1466.67,1331.58,...,1868.18,1818.75,1900.00,1988.89,2061.11,2085.71,2196.88,2215.79,2387.50,2451.90
14,15,"Gari white,sold loose",208.10,270.37,304.94,280.03,282.70,317.60,319.90,334.96,...,306.89,347.37,356.70,360.21,344.96,340.02,358.40,356.15,372.89,374.93
15,16,"Gari yellow,sold loose",264.82,267.65,317.41,302.72,313.43,347.77,366.57,370.38,...,277.17,312.79,363.29,366.21,367.85,368.24,390.29,399.31,481.98,490.56
16,17,Mudfish (aro) fresh,1132.35,1480.63,1313.64,1088.89,1050.00,1057.52,1180.00,1162.50,...,1180.00,1150.00,1219.85,1222.73,1321.43,1470.00,1437.48,1451.62,1577.78,1617.46
17,18,Mudfish : dried,2475.72,2169.01,2206.00,2215.99,2331.72,2204.17,2405.77,2464.29,...,1837.72,1906.21,1833.33,1764.29,1850.71,2025.87,2170.22,2203.57,2327.14,2378.57
18,19,Onion bulb,294.95,315.80,322.45,285.21,287.30,294.36,283.69,397.35,...,234.02,280.39,313.02,342.25,431.19,444.80,419.28,463.56,500.30,609.37
19,20,Rice agric sold loose,298.78,429.57,392.51,369.78,379.26,376.03,363.02,337.75,...,420.66,424.98,434.13,464.05,480.21,507.34,470.29,479.48,509.10,555.81
20,21,Rice local sold loose,321.03,359.37,344.44,345.00,391.67,400.00,399.50,367.98,...,416.70,406.52,434.57,418.27,405.76,426.25,432.67,444.55,445.67,503.15
21,22,Rice Medium Grained,280.82,340.33,322.12,322.58,330.12,336.35,317.54,324.25,...,385.45,345.16,349.35,442.00,506.67,515.00,521.00,525.00,600.00,600.00
22,23,"Rice,imported high quality sold loose",402.54,417.94,386.96,329.84,370.33,371.20,383.14,319.24,...,536.24,595.65,563.67,661.72,604.08,607.36,610.95,629.32,663.59,697.66
23,24,Tomato,300.00,534.61,456.36,450.00,522.49,527.64,566.98,587.27,...,230.12,301.15,309.72,335.64,370.90,376.44,331.00,356.44,428.01,554.76
24,25,Yam tuber,209.06,216.46,221.47,233.42,297.70,302.36,303.43,312.87,...,303.50,316.56,316.71,342.63,407.39,467.18,464.87,476.78,600.27,623.02
25,26,Dried Fish Sardine,1998.22,1976.39,1921.17,1921.48,1993.36,1981.11,1993.06,1924.07,...,1112.50,1105.56,1183.33,1258.25,1319.50,1304.44,1355.70,1400.00,1278.41,1383.33
26,27,Iced Sardine,820.80,817.02,814.21,828.89,828.82,813.12,831.25,848.42,...,980.00,942.47,961.11,1019.23,1035.90,1251.28,1233.61,1233.33,1300.00,1375.00
27,28,Irish potato,326.94,320.42,325.64,321.98,320.20,328.92,327.52,335.12,...,481.99,473.22,471.22,520.43,570.56,518.93,525.94,553.98,632.37,843.02
28,29,Sweet potato,137.91,135.68,138.25,138.97,139.04,144.97,146.52,148.18,...,236.76,232.66,235.96,268.53,268.99,241.20,246.65,269.27,246.19,350.44
29,30,Tilapia fish (epiya) fresh,864.48,949.40,956.95,942.13,938.57,1012.15,1057.74,1038.20,...,1094.51,1034.14,1058.33,1168.75,1213.33,1450.35,1528.57,1594.44,1730.77,1844.44
30,31,Titus:frozen,929.50,933.64,972.92,931.68,981.68,1063.57,1058.89,1051.11,...,1021.74,1109.52,1131.58,1238.11,1354.47,1326.67,1433.98,1473.64,1530.30,1590.91
31,32,Catfish (obokun) fresh,1239.16,1297.93,1259.55,1332.69,1394.20,1390.84,1395.04,1396.70,...,1394.78,1381.25,1364.74,1408.33,1460.71,1652.38,1767.08,1784.44,1821.20,1856.99
32,33,Catfish :dried,2252.65,2300.35,2369.82,2359.63,2365.06,2404.51,2400.69,2400.00,...,1722.73,1745.03,1798.40,1752.38,1845.24,2060.00,2061.04,2089.01,2218.18,2346.10
33,34,Catfish Smoked,1554.26,1576.92,1575.00,1509.26,1500.50,1513.64,1522.30,1526.37,...,1633.33,1675.00,1687.14,1686.80,1778.61,1889.47,1812.38,1830.00,1850.79,1850.79
34,35,Mackerel : frozen,1030.19,993.01,987.50,1067.59,1049.43,1051.37,1094.03,1065.34,...,1064.71,1095.00,1121.05,1227.21,1236.92,1225.00,1284.06,1233.06,1296.88,1280.95
35,36,"Groundnut oil: 1 bottle, specify bottle",483.30,486.66,492.22,500.00,504.13,484.44,480.00,500.00,...,533.33,583.33,580.00,653.34,726.67,833.33,966.67,971.11,996.00,1066.67
36,37,Maize grain white sold loose,222.99,219.01,224.22,236.16,242.02,244.87,269.29,244.56,...,302.49,312.43,356.20,359.21,340.20,356.66,362.59,326.49,400.00,557.43
37,38,Maize grain yellow sold loose,221.35,232.54,224.85,242.80,245.88,252.72,279.65,263.04,...,265.03,278.88,358.22,365.58,349.19,370.48,348.53,343.78,450.00,403.18
38,39,"Palm oil: 1 bottle,specify bottle",410.50,423.56,472.48,508.85,500.00,518.52,523.80,550.00,...,654.55,673.33,679.82,720.64,810.00,831.11,811.76,851.33,977.78,985.34
39,40,Plantain(ripe),302.21,300.00,287.36,261.97,243.92,255.28,276.84,234.50,...,394.50,390.39,388.61,391.81,379.22,364.42,411.38,356.19,367.50,381.31
40,41,Plantain(unripe),307.14,284.35,283.09,292.20,283.11,286.05,270.61,256.92,...,291.81,301.47,389.01,410.15,354.03,348.72,331.42,359.61,382.93,401.20
41,42,"Vegetable oil:1 bottle,specify bottle",598.42,507.26,538.18,552.81,559.14,550.00,555.55,578.57,...,715.87,748.15,755.56,836.67,918.89,930.48,925.93,950.00,1025.00,1078.21
42,43,Wheat flour: prepacked (golden penny 2kg),636.66,666.27,631.25,625.79,622.55,639.04,639.44,644.09,...,707.50,730.56,776.47,765.79,819.44,870.00,900.00,950.00,980.00,995.00

**3. OUTLINE THE REQUIRED COLUMNS:** In this analysis, We will only be making use of the id, ItemLabels, 20-Dec, 21-Nov and 21-Dec columns.

In [4]:
lagos_rice_prices = pd.read_csv(filename,
                                usecols = ['id', 'ItemLabels', '20-Dec','21-Nov', '21-Dec'],
                                 )

lagos_rice_prices

    id                                 ItemLabels   20-Dec   21-Nov   21-Dec
0    1                     Agric eggs medium size   537.22   740.06   763.33
1    2       Agric eggs(medium size price of one)    45.00    70.00    73.18
2    3                     Beans brown,sold loose   292.01   440.54   449.63
3    4          Beans:white black eye. sold loose   359.47   500.86   511.18
4    5                               Beef Bone in  1222.97  1500.72  1520.81
5    6                              Beef,boneless  1373.85  1678.65  1700.00
6    7                          Bread sliced 500g   344.44   412.50   428.50
7    8                        Bread unsliced 500g   286.11   408.33   379.55
8    9                        Broken Rice (Ofada)   810.19   842.50   850.25
9   10                               Chicken Feet   840.00  1060.33  1060.33
10  11                              Chicken Wings  1126.47  1526.11  1604.76
11  12      Evaporated tinned milk carnation 170g   180.00   216.67   240.00
12  13         Evaporated tinned milk(peak), 170g   201.67   268.89   279.39
13  14                             Frozen chicken  1800.00  2387.50  2451.90
14  15                      Gari white,sold loose   253.21   372.89   374.93
15  16                     Gari yellow,sold loose   235.18   481.98   490.56
16  17                        Mudfish (aro) fresh  1212.50  1577.78  1617.46
17  18                            Mudfish : dried  1740.91  2327.14  2378.57
18  19                                 Onion bulb   224.09   500.30   609.37
19  20                      Rice agric sold loose   439.64   509.10   555.81
20  21                      Rice local sold loose   443.12   445.67   503.15
21  22                        Rice Medium Grained   375.00   600.00   600.00
22  23      Rice,imported high quality sold loose   539.24   663.59   697.66
23  24                                     Tomato   266.39   428.01   554.76
24  25                                  Yam tuber   283.44   600.27   623.02
25  26                         Dried Fish Sardine  1187.41  1278.41  1383.33
26  27                               Iced Sardine   938.53  1300.00  1375.00
27  28                               Irish potato   476.36   632.37   843.02
28  29                               Sweet potato   226.06   246.19   350.44
29  30                 Tilapia fish (epiya) fresh  1006.10  1730.77  1844.44
30  31                               Titus:frozen  1058.89  1530.30  1590.91
31  32                     Catfish (obokun) fresh  1399.40  1821.20  1856.99
32  33                             Catfish :dried  1712.59  2218.18  2346.10
33  34                             Catfish Smoked  1540.00  1850.79  1850.79
34  35                          Mackerel : frozen  1057.63  1296.88  1280.95
35  36    Groundnut oil: 1 bottle, specify bottle   533.33   996.00  1066.67
36  37               Maize grain white sold loose   257.27   400.00   557.43
37  38              Maize grain yellow sold loose   259.42   450.00   403.18
38  39          Palm oil: 1 bottle,specify bottle   681.48   977.78   985.34
39  40                             Plantain(ripe)   341.33   367.50   381.31
40  41                           Plantain(unripe)   291.09   382.93   401.20
41  42      Vegetable oil:1 bottle,specify bottle   757.78  1025.00  1078.21
42  43  Wheat flour: prepacked (golden penny 2kg)   653.89   980.00   995.00

**4. OUTLINE THE REQUIRED ROWS:** In this analysis, we will only be making use of the 4 different species of Rice.

In [5]:
lagos_rice_prices = pd.read_csv(filename,
                                usecols = ['id', 'ItemLabels', '20-Dec','21-Nov', '21-Dec'],
                               index_col =  'id',
                                skipfooter = 20,
                                engine ='python'
                               )

lagos_rice_prices = lagos_rice_prices [19:23]

lagos_rice_prices

                               ItemLabels  20-Dec  21-Nov  21-Dec
id
20                  Rice agric sold loose  439.64  509.10  555.81
21                  Rice local sold loose  443.12  445.67  503.15
22                    Rice Medium Grained  375.00  600.00  600.00
23  Rice,imported high quality sold loose  539.24  663.59  697.66

**5. RENAME THE COLUMNS**

In [6]:
lagos_rice_prices.rename(columns = {'ItemLabels' : 'rice_specie',
                                    '20-Dec' : 'dec_2020',
                                    '21-Nov' : 'nov_2021',
                                    '21-Dec' : 'dec_2021'})

                              rice_specie  dec_2020  nov_2021  dec_2021
id
20                  Rice agric sold loose    439.64    509.10    555.81
21                  Rice local sold loose    443.12    445.67    503.15
22                    Rice Medium Grained    375.00    600.00    600.00
23  Rice,imported high quality sold loose    539.24    663.59    697.66

**6. CHECK THE REQIRED INFORMATION:** 
We use:

**The .dtype function** to ensure that all the columns have the correct data type.


**The .info() function** prints information about the dataset. 
The information contains:
- The number of columns
- The column labels
- The column data types
- The memory usage
- The range index
- The number of cells in each column (non-null values)

In [8]:
lagos_rice_prices.dtypes

ItemLabels     object
20-Dec        float64
21-Nov        float64
21-Dec        float64
dtype: object

In [9]:
lagos_rice_prices.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 20 to 23
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ItemLabels  4 non-null      object
 1   20-Dec      4 non-null      float64
 2   21-Nov      4 non-null      float64
 3   21-Dec      4 non-null      float64
dtypes: float64(3), object(1)
memory usage: 160.0+ bytes

**7. NULL VALUES:** Generate the total number of null values available in each column

We have 0 null values available

In [11]:
lagos_rice_prices.isnull().sum()

ItemLabels    0
20-Dec        0
21-Nov        0
21-Dec        0
dtype: int64

**8. SAVE THE DATA**

In [12]:
lagos_rice_prices

                               ItemLabels  20-Dec  21-Nov  21-Dec
id
20                  Rice agric sold loose  439.64  509.10  555.81
21                  Rice local sold loose  443.12  445.67  503.15
22                    Rice Medium Grained  375.00  600.00  600.00
23  Rice,imported high quality sold loose  539.24  663.59  697.66

In [13]:
lagos_rice_prices.to_csv('C:/Users/HP/Desktop/DATA SET/lagos_food_prices')